{
 "title": "Team",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "team_name",
    "label": "Team name",
    "query": {
     "query": "ctf_manager.teams.find(\n  {},\n  { _id: 0, name: 1 }\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Scores",
   "type": "bargauge",
   "description": "Total points earned (score) by each team",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "ctf_manager.teams.aggregate([{\"$unwind\":{\"path\":\"$flags\",\"preserveNullAndEmptyArrays\":true}},{\"$group\":{\"_id\":\"$name\",\"earnedPoints\":{\"$sum\":{\"$cond\":[{\"$eq\":[\"$flags.found\",true]},\"$flags.points\",0]}},\"maxPoints\":{\"$sum\":\"$flags.points\"}}},{\"$project\":{\"_id\":0,\"team\":\"$_id\",\"earnedPoints\":1,\"maxPoints\":1}}])",
     "query": "ctf_manager.teams.aggregate([\n  // Décompose le tableau \"flags\" pour traiter chaque élément individuellement\n  { $unwind: { path: \"$flags\", preserveNullAndEmptyArrays: true } },\n  // Regroupe par équipe pour calculer earnedPoints et maxPoints\n  { $group: {\n    _id: \"$name\",\n    earnedPoints: { \n      $sum: { \n        $cond: [{ $eq: [\"$flags.found\", true] }, \"$flags.points\", 0] \n      }\n    },\n    maxPoints: {\n      $sum: \"$flags.points\"\n    }\n  }},\n  // Renomme le champ _id en \"team\" pour plus de clarté\n  { $project: {\n    _id: 0,\n    team: \"$_id\",\n    earnedPoints: 1,\n    maxPoints: 1\n  }}\n])"
    }
   ]
  },
  {
   "title": "Founded flags",
   "type": "table",
   "description": "All flags found by teams",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "parsedQuery": "ctf_manager.teams.aggregate([{\"$unwind\":{\"path\":\"$flags\",\"preserveNullAndEmptyArrays\":true}},{\"$group\":{\"_id\":{\"team\":\"$name\",\"flagName\":\"$flags.name\",\"order\":\"$flags.order\"},\"found\":{\"$max\":{\"$ifNull\":[\"$flags.found\",false]}}}},{\"$project\":{\"_id\":0,\"team\":\"$_id.team\",\"flag\":\"$_id.flagName\",\"order\":\"$_id.order\",\"found\":1}}])",
     "query": "ctf_manager.teams.aggregate([\n  // Décompose le tableau \"flags\" pour traiter chaque élément individuellement\n  { $unwind: { path: \"$flags\", preserveNullAndEmptyArrays: true } },\n  // Regroupe par équipe et projette les champs nécessaires\n  { $group: {\n    _id: { team: \"$name\", flagName: \"$flags.name\", order: \"$flags.order\" },\n    found: { $max: { $ifNull: [\"$flags.found\", false] } }\n  }},\n  // Projette les champs finaux\n  { $project: {\n    _id: 0,\n    team: \"$_id.team\",\n    flag: \"$_id.flagName\",\n    order: \"$_id.order\",\n    found: 1\n  }}\n])"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "parsedQuery": "ctf_manager.teams.aggregate([{\"$unwind\":{\"path\":\"$flags\",\"preserveNullAndEmptyArrays\":true}},{\"$match\":{\"flags.found\":true}},{\"$group\":{\"_id\":{\"team\":\"$name\",\"flagName\":\"$flags.name\",\"order\":\"$flags.order\",\"found_at\":\"$flags.found_at\",\"points\":\"$flags.points\"},\"found\":{\"$first\":\"$flags.found\"}}},{\"$project\":{\"_id\":0,\"team\":\"$_id.team\",\"flag\":\"$_id.flagName\",\"order\":\"$_id.order\",\"found\":1,\"found_at\":\"$_id.found_at\",\"points\":\"$_id.points\"}}])",
     "query": "ctf_manager.teams.aggregate([\n  // Décompose le tableau \"flags\" pour traiter chaque élément individuellement\n  { $unwind: { path: \"$flags\", preserveNullAndEmptyArrays: true } },\n  // Filtre pour ne garder que les flags trouvés\n  { $match: { \"flags.found\": true } },\n  // Regroupe par équipe et projette les champs nécessaires\n  { $group: {\n    _id: {\n      team: \"$name\",\n      flagName: \"$flags.name\",\n      order: \"$flags.order\",\n      found_at: \"$flags.found_at\",\n      points: \"$flags.points\"\n    },\n    found: { $first: \"$flags.found\" }\n  }},\n  // Projette les champs finaux\n  { $project: {\n    _id: 0,\n    team: \"$_id.team\",\n    flag: \"$_id.flagName\",\n    order: \"$_id.order\",\n    found: 1,\n    found_at: \"$_id.found_at\",\n    points: \"$_id.points\"\n  }}\n])"
    }
   ]
  }
 ]
}